services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: retail
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: ch-ui
    ports:
      - "5521:3488"
    environment:
      CLICKHOUSE_URL: "http://clickhouse:8123"
      CONNECTION_NAME: "Local ClickHouse"
    depends_on:
      - clickhouse

volumes:
  clickhouse_data: